### ISSUE TITLE
Additional include folders don't seem to be working

### ISSUE THREAD

**Issue by Sl3dge78** [DonaldHays/rgbds-vscode#11]
Or maybe I'm doing something wrong?

Here's my project structure : 
```
root  
   |- src (main.asm, memory.asm,)  
   |- include (hardware.inc)  
 build.bat  
```

in main.asm at the top I have :
```
include "include/hardware.inc"     
include "src/memory.asm"
```

And in my settings.json 
```
  "rgbdsz80.includePath": [
        "src/",
        "include/"
    ]
```
My build.bat builds from the root, so all the files I include are included relative to the root, instead of the current file :
```
"../asm/rgbasm" -o tmp/temp.o src/main.asm
"../asm/rgblink" -o build.gb tmp/temp.o
"../asm/rgbfix" -v -p 0 build.gb
```
I couldn't get auto completion for included files working in this config. I tried multiple entries in rgbdsz80.includePath to no avail :
- /src/
- src/
- ./src/
- ${workspaceFolder}/src/
- ../

Thank you!

**Comment by DonaldHays** [comment]
Took me a while to figure this one out, the answer's definitely not obvious!

I think this is what you want:

```json
"rgbdsz80.includePath": [
  ""
]
```

I tried replicating your setup, and that includePath seemed to do what you want. I was able to see definitions from `hardware.inc` while editing inside `memory.asm`, for example.

**Comment by Sl3dge78** [comment]
Works great thank you for the clarification!

**Comment by TheRektafire** [comment]
Hm I'm having this issue as well and putting my files in the exact same places and with the exact same include path of "" doesnt fix it... I have the project opened in the root in vscode where I see my `src`, `assets`, etc folders and I moved my main.asm and hardware.inc to the exact places @Sl3dge78 had them (they were somewhere else but I moved them in the hopes it would fix it) but it still doesnt work... not only that but when I go to include the file the extension puts \ in the files which definitely doesnt seem right and which I replace with /... which also doesnt fix it, could this be a windows specific issue or am I just not doing something right either. Also if it matters I'm using the version on the marketplace not from the repo

**Comment by DonaldHays** [comment]
@TheRektafire I tried replicating the structure on Windows, and I'm unable to reproduce your problem, it seems to work correctly there, too. I've attached a zip file (prepared in Windows) showing a minimal working example project. The include path is configured in `.vscode/settings.json`, then `src/main.asm` includes `"src/hardware.inc"`, which declares `myDef`, which then appears in code completion prompts in `src/main.asm` when I begin typing `myDef`.

[gbtest.zip](https://github.com/DonaldHays/rgbds-vscode/files/6682927/gbtest.zip)

**Comment by DonaldHays** [comment]
@TheRektafire Issue #12 has brought to my attention that `hardware.inc` has been updated to the new definition syntax from RGBDS 0.5.0, which my extension doesn't yet support. This would make the defines fail to appear in Intellisense prompts, even if your include path is correctly defined. I hope to have an update supporting the new definition syntax out later today.

**Comment by TheRektafire** [comment]
Lol I was a little late on receiving the email notification for your reply but thanks 😆 I noticed it was working with my own code but not with hardware.inc which I thought was weird, guess that's why
