### ISSUE TITLE
New version of hardware.inc doesn't work

### ISSUE THREAD

**Issue by Smelly-Ghost** [DonaldHays/rgbds-vscode#12]
The newest version of the [gbdev maintained hardware.inc](https://github.com/gbdev/hardware.inc) recently updated to use the RGBDS v0.5.0 `DEF` syntax. This seems to break this extension's ability to read the include file. Swapping back to a previous version of the hardware.inc file prior to this change makes it work again. However, to keep up to date I think it'd be good to support the currently maintained version. 

Please let me know if you need any other information.

**Comment by DonaldHays** [comment]
I've been slower than I should be getting the new syntax in 0.5.0 implemented. I was planning to put more work in over the next few days anyway, and the new `def` syntax was next on my list, but if `hardware.inc` stopped working correctly on the current version, I think that's reason enough to not only implement that feature tomorrow, but to ship a release with it before GB Compo 2021 begins. Thanks for letting me know, this is now a high priority for me!

**Comment by Smelly-Ghost** [comment]
Yeah I tried setting up my environment last night and grabbed the newest version and I couldn't get any of the IntelliSense working for the hardware.inc until I went back to the previous version and figured out what had changed. Thanks!
