### ISSUE TITLE
Capitalization rules affect within word boundaries

### ISSUE THREAD

**Issue by zimmydev** [DonaldHays/rgbds-vscode#13]
The extension's autocapitalization features incorrectly changes preprocessor directives that it finds within label names.

For example, if my `language.keyword.preprocessor` is set to `"upper"`, then I cannot save a file with a routine called `MemSet`, because it incorrectly gets changed to `MemSET`. Only the label itself is changed (not where it is referenced), breaking labels since they are case-sensitive.

**Comment by DonaldHays** [comment]
Thanks for the report!

This should be fixed in 3.0.1, which just went live.

Please let me know if it fixed the issue!

**Comment by zimmydev** [comment]
Issue fixed! Thanks for the speedy update.

**Comment by zimmydev** [comment]
Unfortunately, the implemented bugfix now makes the `language.keyword.preprocessor` setting powerless against the `SET` preprocessor directive, which now gets lowercased no matter what the setting is set to.

**Comment by Rangi42** [comment]
`SET` has been removed as a directive as of rgbds 0.5.2; now you always use `=` for that, and `set` is always the opcode.

**Comment by DonaldHays** [comment]
@Rangi42 unless I'm mistaken, `SET` is currently deprecated, not removed. You can still use it, you'll just get a deprecation warning.

Because of that, my current intention is to continue supporting it in the VSCode extension for now, leaving it to the assembler to flag it as a warning (which it does).

For that reason, I'm opening the ticket back up to fix the regression.

**Comment by DonaldHays** [comment]
@zimmydev do you have an example of the `SET` preprocessor directive not being formatted correctly?

If I write `myConst set 3` with `"language.keyword.preprocessor": "upper"` configured, I get `myConst SET 3`.

**Comment by zimmydev** [comment]
I do not! It seems I was confusing the `SET` and `DEF` directives. All seems good.

**Comment by zimmydev** [comment]
I do not! It seems I was confusing the SET and DEF directives. All seems good.
