### ISSUE TITLE
Numbers with underscores not recognized

### ISSUE THREAD

**Issue by zimmydev** [DonaldHays/rgbds-vscode#15]
Syntax highlighting seems to break when introducing a `_` separator into numeric literals.

This is valid RGBASM syntax and should probably be highlighted.

Not a huge issue, but probably an easy fix so I thought I'd mention this.

**Comment by DonaldHays** [comment]
This issue, along with #14, should be fixed in 3.1.0, available now!

**Comment by zimmydev** [comment]
Thanks, everything seems to be working now! 👍🏻

**Comment by zimmydev** [comment]
Thanks, everything seems to be working now! 👍🏻
