### ISSUE TITLE
Comments starting with * are not recognized as comments

### ISSUE THREAD

**Issue by DaKnig** [DonaldHays/rgbds-vscode#4]
According to the `man 5 rgbasm`: 'anything that follows a "*" that is placed right at the start of a line is a comment'. rgbds does not currently support this kind of comments. That is an obscure feature of rgbds, maybe. But it shouldn't be too hard to implement .

**Comment by DonaldHays** [comment]
I'm trying it out, and I'm getting compile errors from rgbasm if I start a line with a "*".

The documentation states it should be valid, but unless I'm missing something it looks like rgbasm doesn't actually support it?

**Comment by DonaldHays** [comment]
Looks like support for asterisk comments was added somewhat recently. I got compile errors on 0.3.5, and they went away when I upgraded to 0.3.7. Will add support for them in the extension.
