### ISSUE TITLE
Completions display formatting bug

### ISSUE THREAD

**Issue by ix** [DonaldHays/rgbds-vscode#6]
Completions seem to have a formatting issue wherein the N flag is displayed on the same line as the Z flag. You can see this in the screenshot below.

![image](https://user-images.githubusercontent.com/1900521/58552868-53947480-820b-11e9-9526-0198ca8cf6da.png)

VSCode version: `1.34.0 a622c65b2c713c890fcf4fbf07cf34049d5fe758 2019-05-15T21:49:51.528Z`
Extension version: `2.4.0 `
Platform: `MacOS 10.14.4`

**Comment by DonaldHays** [comment]
Thanks for reporting this issue! I confirmed it, believe I have fixed it, and pushed the fix into an update that should be deploying momentarily.

After you update to 2.4.1, I would appreciate if you could reply to this issue indicating whether or not the issue appears fixed to you.

Thanks again!

**Comment by ix** [comment]
I've updated and can confirm it's resolved! Many thanks for the speedy fix, and for creating such a useful extension in the first place. 

![image](https://user-images.githubusercontent.com/1900521/58649934-5a9fad80-8305-11e9-805f-ab0583f458d3.png)
